### ISSUE TITLE
List down all possible data sources to consider for OpenDS

### ISSUE THREAD

**Issue by sameeravithana** [scorelab/OpenXDR#1]
- [ ] List all possible data-sources with identified integration (e.g. package, third-party tool etc) 
- [ ] Come up with a strategic plan to embed data sources to OpenADS space

**Comment by charithccmc** [comment]
**Possible data-sources**
- PCAP
- Syslog
- Bro
- Snort
- DPI - BRO
- NetFlow
- Lancope
- BlueCoat
- FireEye
- ISE
- Palo Alto
- Source Fire
- YAF

**Comment by xiaoleihuang** [comment]
I hold an strategy for integrating data sources in #1 issue. Overall, we could define some frameworks and management models. I can call my idea as Tree method, such as Decision Tree in ML. Here is the idea below:
     1. We first need to define one basic flexible data schema(json or database whatever) for whole data sources. Schema: id, title; data source(from which input source); time; data type. Data type will be defined in the following. 
     2. Different data sources do have different data types such as numbers, texts, or even pictures. However, some data sources or groups of them will share similar attributes, such as they are all texts or they share similar data types. So the second layer will be cluster similar data source schemas into different groups since now we only own some limited data sources. In this layer, we can define more specific data attributes: attach sources; IP, etc. Indeed, whenever we need, we can define new schemas to define new input data sources and group them together. 
     3. Even we will have multiple layers of data schemas, but oeverall, we share an united one framework and part of similar data attributes, similar to interface in Java.

Data types are very important for feature automatic extraction. Like text mining, we may use tf-idf or LDA. Like numbers, we might discretize them into different levels.This is why I mentioned one of important attributes of data schema, "data type". In addition, grouping similar data schemas could guide the framework determines which tool is more appropriate in processing workflow. The tool can automatically process the data when the data type is clear. 

This is just my prototype idea, that is to say, immature one. We may extend it later.

BTW, it may also leave some hints on solving the #2 issue.

**Comment by sameeravithana** [comment]
Idea on tree-based data-structure does make sense over dynamic data-sources. But I guess that modern day index structures would help us, like Elasticsearch; We can populate different structures of data to Elasticsearch and it can be considered as a streaming source where we capture all events via a generic query API, This is quite different in other architectures where specific index structure would consider at the end of the system flow as a storage.
Elasticsearch as a stream: https://github.com/hmalphettes/elasticsearch-streams

**Comment by xiaoleihuang** [comment]
Using Elasticsearch is a great way to store data! Yeah, with powerful REST service, specific _index and _type fields provide our program a flexible way to store and retrieve the data! I had experience in building search engine with Lucene. Sorry for the delaying reply due to my thesis deadline approaches in this weekend.

**Comment by sameeravithana** [comment]
Looking forward the general ES index structure, supported by OpenADS in your proposal

**Comment by xiaoleihuang** [comment]
There is a good package named ["kraken" ](https://github.com/nchovy/kraken)
This package could be used to receive syslog messages.

**Comment by xiaoleihuang** [comment]
https://drive.google.com/file/d/0ByOnGX8_xfRrSUxhN2ViSFdOUlU/view?usp=sharing

Hi, I uploaded a file that contains possible open source tools for analyzing those data. Yet, this file is not completed, we could collaborate editing on it later.
