### ISSUE TITLE
Design mock dashboard for OpenADS

### ISSUE THREAD

**Issue by sameeravithana** [scorelab/OpenXDR#8]
In the long run, we need to have a single dashboard to monitor incoming packets, filtering, visualization and analysis, This task is to come up with UI features

**Comment by xiaoleihuang** [comment]
Some ideas with continuous update in this documents:
[Some ideas and concerns](https://drive.google.com/file/d/0ByOnGX8_xfRrbjloU3pjNEEtQ2s/view?usp=sharing)

**Comment by Ammoniya** [comment]
archive
